version: '3.4'

services:

  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=password
    volumes:
      - keycloak:/var/lib/postgresql/data

  keycloak:
    image: jboss/keycloak:latest
    environment:
      - DB_VENDOR=postgres
      - DB_ADDR=postgres
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DB_PASSWORD=password
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
    volumes:
      - /home/dominique/Documents/sharewood-locksmith/tmp:/tmp
    ports:
      - 8080:8080
    depends_on:
      - postgres

 

volumes:

  keycloak:
    external: true
    name: keycloak-data
  
      


